This adds a geography map to my main webpage and allows the user to select from which continent they are from
SantiAce26/my-portfolio pull request #6
Opened 2021-03-09 20:31 UTC by SantiAce26

Hi! So this is supposed to add a geography map that shows where users who have visited the website are from.

2021-03-11 03:21 UTC, kuanyiwu requested changes
This is a cool functionality! The chart should render after you make a few changes.

2021-03-11 03:21 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
> +    fetch('/geography-data').then(response => response.json()).then((geoGraphyCount) => {
Rename `geoGraphyCount` to `geographyCount`.

2021-03-11 03:21 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
> +        data.addColumn('String','Continent');
`String` to `string`
Data type in DataTable is lower cased.

2021-03-11 03:21 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
> +        data.addColumn('Number','People');
`Number` to `number`

2021-03-11 03:21 UTC, kuanyiwu commented on portfolio/src/main/webapp/index.html
> +                <option value="North America">North America</option>
Region mode of Geochart does not support continents, Australia should work. See the Data Format section in [Geochart](https://developers.google.com/chart/interactive/docs/gallery/geochart).

2021-03-12 22:43 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
>          const chart = new google.visualization.GeoChart(document.getElementById('regions-div'));
Is the Google Maps Javascript API activated on your project? I've been getting the following error. 
https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error

2021-03-12 22:43 UTC, kuanyiwu commented on portfolio/src/main/webapp/styleAboutMe.css
> +@import url('https://fonts.googleapis.com/css2?family=Dekko&family=Lato:wght@900&family=Rock+Salt&display=swap');
The two new css files are duplicated from style.css. You can import style.css into the aboutme or projects pages.

2021-03-13 00:35 UTC, SantiAce26 commented on portfolio/src/main/webapp/script.js
>          const chart = new google.visualization.GeoChart(document.getElementById('regions-div'));
I do not have the google maps api activated, let me commit all my files to see if that helps. Very weird though

2021-03-15 20:22 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
>          const chart = new google.visualization.GeoChart(document.getElementById('regions-div'));
Does the map render when you preview it?

2021-03-15 21:15 UTC, SantiAce26 commented on portfolio/src/main/webapp/script.js
>          const chart = new google.visualization.GeoChart(document.getElementById('regions-div'));
Yeah it does, I even deployed it and it runs fine on there too

2021-03-15 22:16 UTC, kuanyiwu commented on portfolio/src/main/webapp/script.js
>          const chart = new google.visualization.GeoChart(document.getElementById('regions-div'));
Ah okay I see this on deployment.

2021-03-15 22:16 UTC, kuanyiwu approved these changes

2021-03-15 23:12 UTC, merged